import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
// import Example from "./components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {

  title: "Ecars",

  description: "Generated by LD",

};



export default function RootLayout({ children }) {

  return (

    <html lang="en">

      <body className={inter.className}>

        <Navbar />

        {children}
        
       {/* <Example/> */}
      </body>

    </html>

  );

}